name: Auto Deploy to VPS

on:
  push:
    branches:
      - main  # Ganti ke 'master' jika branch utama kamu bernama master

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Execute Deploy Script on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            /home/clingdental_kasirftp/deploy.sh
